name: cangjie test

on:
  issues: 
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-22.04

    steps:
     

      - name: clone
        run: git clone https://github.com/HLBZQD/cangjiedemo.git
        
      - name: test
        run: source cangjie/envsetup.sh && cjc --version && cd cangjiedemo && cjpm update && cjpm build && cjpm test
  
