name: cangjie test

on:
  issues: 
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-22.04

    steps:
      - name: download
        run: wget "https://cangjie-lang.cn/v1/files/auth/downLoad?nsId=142267&fileName=cangjie-sdk-linux-x64-1.1.3.tar.gz&objectKey=6a19349d21f5a8178d6fd22b" -q -O cangjie-sdk-linux-x64-1.1.3.tar.gz && tar -xzf cangjie-sdk-linux-x64-1.1.3.tar.gz

      - uses: actions/checkout@v7.0.0
        
        
      - name: test
        run: source cangjie/envsetup.sh && cjc --version && cd cangjiedemo && cjpm update && cjpm build && cjpm test
  
